a=input("请输你的名字：")

c=input("您的性别：")
if(c=="男"):
   print("\n勇士好")
else:
    print("\n女神好")
d=input("\n您的年龄：")
e=int(d)
if(e<=20):
  print("少年英雄好")
else:
      print("老江湖好")
point=1
c=input("开始游戏，Let'go!\n目前你在大门\n请选择下一步位置:1:左路2:右路")
while(1):
 if(c=="1"):
   print("欢迎来到地狱")
   point=1
   break
 if(c=="2"):
   print("欢迎来到天堂")
   point=2
   break
